language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update
    - export PLATFORMIO_CI_SRC=src
    - export PLATFORMIO_BUILD_FLAGS="-D NOLCD"

script:
    - platformio ci --project-conf=platformio.ini
